### ISSUE TITLE
npm 包缺少 lib 文件夹

### ISSUE THREAD

**Issue by sinchang** [1021683053/egg-view-art#3]
你好，麻烦检查下，我在开发过程中报错找不到 `./lib/view`。

**Comment by 1021683053** [comment]
好的，我晚上回去改一下，你如果有时间改一下也行.

**Comment by sinchang** [comment]
嗯 我自己先改了 因为要依赖你的包 所以麻烦你再传一版到 npm。

**Comment by 1021683053** [comment]
你能把报错截图，或者配置截图一下吗？我这边没有遇到错误！

**Comment by sinchang** [comment]
![](https://ws3.sinaimg.cn/large/006tNc79gy1flokvmnf8cj30hp02kdg1.jpg)

这是我从 npm download 下来的文件，少了 lib 文件夹。

**Comment by 1021683053** [comment]
这就扯了，怎么可能呢！我直安装都好好的，.npmignore保佑包含 lib文件夹！
这样吧我把这个测试写完吧！下午六七点我再发一次！

**Comment by 1021683053** [comment]
你看看你那好不好用！我这好用的！

**Comment by sinchang** [comment]
感谢，包正常了。
